sudo: required
services:
  - docker
before_install:
  - docker build -t diedsmiling/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true diedsmiling/docker-react npm run test
language: generic